---
- hosts:
    - vagrant
  gather_facts: false
  become: true
  pre_tasks:
    - name: Gather facts
      setup:


    #-----------
    # set hostname
    #-----------
  roles:
    - role: cockroachdb
      tags: cockroachdb
